-- Language Config Only Change the words on the right--


-- English Translation, other languages below --
if CLIENT then

	sugar_boom.Lang = sugar_boom.Lang or {}

	sugar_boom.Lang["Search"] = "Search"
	sugar_boom.Lang["Community"] = "Community"
	sugar_boom.Lang["View History"] = "View History"
	sugar_boom.Lang["View Favorites"] = "View Favorites"
	sugar_boom.Lang["Settings"] = "Settings"
	sugar_boom.Lang["Stop Song"] = "Stop Song"
	sugar_boom.Lang["Stopping song!"] = "Stopping song!"
	sugar_boom.Lang["History"] = "History"
	sugar_boom.Lang["Favorites"] = "Favorites"
	sugar_boom.Lang["InvalidAPIKey"] = "Your server host never input an API key! This addon won't work without it!"
	sugar_boom.Lang["Lock Boombox"] = "Lock Boombox"
	sugar_boom.Lang["Disable All Boombox Audio"] = "Disable All Boombox Audio"
	sugar_boom.Lang["You will no longer be able to hear boombox audio"] = "You will no longer be able to hear boombox audio"
	sugar_boom.Lang["You will be able to now hear boombox audio"] = "You will be able to now hear boombox audio"
	sugar_boom.Lang["Enable All Boombox Audio"] = "Enable All Boombox Audio"
	sugar_boom.Lang["Disable All Boombox Audio"] = "Disable All Boombox Audio"
	sugar_boom.Lang["Play Songs Local"] = "Play Songs Local"
	sugar_boom.Lang["Boombox songs will only play for you"] = "Boombox songs will only play for you"
	sugar_boom.Lang["Play Songs For Everyone"] = "Play Songs For Everyone"
	sugar_boom.Lang["Boombox songs will only play for everyone around your boombox"] = "Boombox songs will only play for everyone around your boombox"
	sugar_boom.Lang["Set Boombox Color"] = "Set Boombox Color"
	sugar_boom.Lang["Clear History"] = "Clear History"
	sugar_boom.Lang["History was cleared"] = "History was cleared"
	sugar_boom.Lang["Rebuild Frame"] = "Rebuild Frame"
	sugar_boom.Lang["Frame will be rebuilt on the next open"] = "Frame will be rebuilt on the next open"
	sugar_boom.Lang["Watched At"] = "Watched At"
	sugar_boom.Lang["Add to favorites"] = "Add to Favorites"
	sugar_boom.Lang["Requested By"] = "Requested By"
	sugar_boom.Lang["Times Played"] = "Times Played"
	sugar_boom.Lang["Favorited At"] = "Favorited At"
	sugar_boom.Lang["Played"] = "Played"
	sugar_boom.Lang["Views"] = "Views"
	sugar_boom.Lang["Likes"] = "Likes"
	sugar_boom.Lang["Dislikes"] = "Dislikes"
	sugar_boom.Lang["This video has "] = "This video has"
	sugar_boom.Lang["no"] = "no"
	sugar_boom.Lang[" steams availible! Try a new one!"] = " steams availible! Try a new one!"
	sugar_boom.Lang["Converting video, please wait up to 30 seconds!"] = "Converting video, please wait up to 30 seconds!"
	sugar_boom.Lang[" time(s)"] = " time(s)"
	sugar_boom.Lang["Please wait "] = "Please wait "
	sugar_boom.Lang[" seconds before doing this!"] = " seconds before doing this!"
	sugar_boom.Lang[" was "] = " was "
	sugar_boom.Lang["added"] = "added"
	sugar_boom.Lang["removed"] = "removed"
	sugar_boom.Lang[" to your favorites!"] = " to your favorites!"
	sugar_boom.Lang["Set on Repeat"] = "Set on Repeat"
	sugar_boom.Lang["Link found, playing now!"] = "Link found, playing now!"
	sugar_boom.Lang["You cannot play videos over 20 minutes!"] = "You cannot play videos over 20 minutes!"
	sugar_boom.Lang["There was an error playing the video"] = "There was an error playing the video"
	sugar_boom.Lang["Length"] = "Duration"
	
	
	
	
	
	-- FRENCH Language Config | BY ⌛ Տบ乃ɑ尺ป ⌛ --
	/* sugar_boom.Lang["Search"] = "Rechercher"
	 sugar_boom.Lang["Community"] = "Communauté"
	 sugar_boom.Lang["View History"] = "Voir l'historique"
	 sugar_boom.Lang["View Favorites"] = "Voir les favoris"
	 sugar_boom.Lang["Settings"] = "Paramètres"
	 sugar_boom.Lang["Stop Song"] = "Arrêter la musique"
	 sugar_boom.Lang["Stopping song!"] = "Arrêt de la musique !"
	 sugar_boom.Lang["History"] = "Historique"
	 sugar_boom.Lang["Favorites"] = "Favoris"
	 sugar_boom.Lang["InvalidAPIKey"] = "L'hôte de votre serveur n'a jamais entré de clé API ! L'addon ne fonctionnera pas sans !"
	 sugar_boom.Lang["Lock Boombox"] = "Verrouiller la Boombox"
	 sugar_boom.Lang["You will no longer be able to hear boombox audio"] = "Vous ne serez plus en mesure d'entendre l'audio de la Boombox"
	 sugar_boom.Lang["You will be able to now hear boombox audio"] = "You will be able to now hear boombox audio"
	 sugar_boom.Lang["Enable All Boombox Audio"] = "Activer tous les fichiers audio de la Boombox"
	 sugar_boom.Lang["Disable All Boombox Audio"] = "Désactiver tous les fichiers audio de la Boombox"
	 sugar_boom.Lang["Play Songs Local"] = "Écouter les musiques en mode local"
	 sugar_boom.Lang["Boombox songs will only play for you"] = "Les musiques de la Boombox ne seront entendu que par vous"
	 sugar_boom.Lang["Play Songs For Everyone"] = "Écouter les musiques en mode public"
	 sugar_boom.Lang["Boombox songs will only play for everyone around your boombox"] = "Les musiques de la Boombox seront entendu par tout les joueurs à proximité"
	 sugar_boom.Lang["Set Boombox Color"] = "Définir la couleur de la Boombox"
	 sugar_boom.Lang["Clear History"] = "Effacer l'historique"
	 sugar_boom.Lang["History was cleared"] = "Historique effacé"
	 sugar_boom.Lang["Rebuild Frame"] = "Reconstruire le cadre "
	 sugar_boom.Lang["Frame will be rebuilt on the next open"] = "Le cadre sera reconstruit à la prochaine ouverture"
	 sugar_boom.Lang["Watched At"] = "Regardé à"
	 sugar_boom.Lang["Add to favorites"] = "Ajouter aux favoris"
	 sugar_boom.Lang["Requested By"] = "Demandé par"
	 sugar_boom.Lang["Times Played"] = "Écouté au total"
	 sugar_boom.Lang["Favorited At"] = "Favorisé à"
	 sugar_boom.Lang["Played"] = "Écouté"
	 sugar_boom.Lang["Views"] = "Vues"
	 sugar_boom.Lang["Likes"] = "Likes"
	 sugar_boom.Lang["Dislikes"] = "Dislikes"
	 sugar_boom.Lang["This video has "] = "Cette vidéo a"
	 sugar_boom.Lang["no"] = "non"
	 sugar_boom.Lang[" steams availible! Try a new one!"] = " flux disponibles ! Essayez en un nouveau !"
	 sugar_boom.Lang["Converting video, please wait up to 30 seconds!"] = "Conversion de la vidéo, veuillez patienter jusqu'à 30 secondes !"
	 sugar_boom.Lang[" time(s)"] = " fois"
	 sugar_boom.Lang["Please wait "] = "Veuillez patienter "
	 sugar_boom.Lang[" seconds before doing this!"] = " secondes de pouvoir faire cela !"
	 sugar_boom.Lang[" was "] = " était "
	 sugar_boom.Lang["added"] = "ajouté"
	 sugar_boom.Lang["removed"] = "supprimé"
	 sugar_boom.Lang[" to your favorites!"] = " a vos favoris !"
	 sugar_boom.Lang["Set on Repeat"] = "Définir sur Répéter"
	 sugar_boom.Lang["Link found, playing now!"] = "Link found, playing now!"	
	 sugar_boom.Lang["You cannot play videos over 20 minutes!"] = "You cannot play videos over 20 minutes!"
	 sugar_boom.Lang["There was an error playing the video"] = "There was an error playing the video"
	 sugar_boom.Lang["Length"] = "Duration"
	*/
	
	
	/* -- POLISH Language Config | BY Djuk --
	sugar_boom.Lang["Search"] = "Szukaj"
    sugar_boom.Lang["Community"] = "Społeczność"
    sugar_boom.Lang["View History"] = "Historia"
    sugar_boom.Lang["View Favorites"] = "Ulubione"
    sugar_boom.Lang["Settings"] = "Ustawienia"
    sugar_boom.Lang["Stop Song"] = "Zatrzymaj"
    sugar_boom.Lang["Stopping song!"] = "Zatrzymuję piosenkę!"
    sugar_boom.Lang["History"] = "Historia"
    sugar_boom.Lang["Favorites"] = "Ulubione"
    sugar_boom.Lang["InvalidAPIKey"] = "Właściciel nie ustawił kluczu api!"
    sugar_boom.Lang["Lock Boombox"] = "Zablokuj radio"
    sugar_boom.Lang["Disable All Boombox Audio"] = "Wyłącz dźwięki radia"
    sugar_boom.Lang["You will no longer be able to hear boombox audio"] = "Nie będziesz już słyszeć radia"
    sugar_boom.Lang["You will be able to now hear boombox audio"] = "Już będziesz słyszeć radio"
    sugar_boom.Lang["Enable All Boombox Audio"] = "Włącz dźwięki radia"
    sugar_boom.Lang["Disable All Boombox Audio"] = "Wyłącz dźwięki radia"
    sugar_boom.Lang["Play Songs Local"] = "Włącz muzykę lokalnie"
    sugar_boom.Lang["Boombox songs will only play for you"] = "Muzykę będziesz słyszeć wyłącznie ty"
    sugar_boom.Lang["Play Songs For Everyone"] = "Włącz muzykę dla wszystkich"
    sugar_boom.Lang["Boombox songs will only play for everyone around your boombox"] = "Muzyka będzie grać dla wszystkich obok twojego radia"
    sugar_boom.Lang["Set Boombox Color"] = "Zmień kolor"
    sugar_boom.Lang["Clear History"] = "Usuń historie"
    sugar_boom.Lang["History was cleared"] = "Historia została usunięta!"
    sugar_boom.Lang["Rebuild Frame"] = "Przebuduj okienko"
    sugar_boom.Lang["Frame will be rebuilt on the next open"] = "Okienko zostanie przebudowane po ponownym otworzeniu radia"
    sugar_boom.Lang["Watched At"] = "Oglądane w dniu"
    sugar_boom.Lang["Add to favorites"] = "Dodaj do ulubionych"
    sugar_boom.Lang["Requested By"] = "Odtwarzane przez"
    sugar_boom.Lang["Times Played"] = "Odtwarzane "
    sugar_boom.Lang["Favorited At"] = "Ulubione w dniu"
    sugar_boom.Lang["Played"] = "Odtworzone"
    sugar_boom.Lang["Views"] = "Wyświetleń"
    sugar_boom.Lang["Likes"] = "Like"
    sugar_boom.Lang["Dislikes"] = "Dislike"
    sugar_boom.Lang["This video has "] = "Ta piosenka ma"
    sugar_boom.Lang["no"] = "nie"
    sugar_boom.Lang[" steams availible! Try a new one!"] = " steams availible! Try a new one!"
    sugar_boom.Lang["Converting video, please wait up to 30 seconds!"] = "Konwertuje piosenkę, poczekaj do 30 sekund!"
    sugar_boom.Lang[" time(s)"] = " razy"
    sugar_boom.Lang["Please wait "] = "Proszę poczekaj "
    sugar_boom.Lang[" seconds before doing this!"] = " sekund przed następną próbą"
    sugar_boom.Lang[" was "] = " zostało "
    sugar_boom.Lang["added"] = "dodane"
    sugar_boom.Lang["removed"] = "usunięte"
    sugar_boom.Lang[" to your favorites!"] = " do twoich ulubionych!"
    sugar_boom.Lang["Set on Repeat"] = "Odtwarzaj w pętli" 
	sugar_boom.Lang["Link found, playing now!"] = "Link found, playing now!"
	sugar_boom.Lang["You cannot play videos over 20 minutes!"] = "You cannot play videos over 20 minutes!"
	sugar_boom.Lang["There was an error playing the video"] = "There was an error playing the video"
	sugar_boom.Lang["Length"] = "Duration"
	*/
	
end